version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: flask_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MyStrongRoot@123
      MYSQL_DATABASE: bsfattendence
      MYSQL_USER: newuser
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - bsf_attendence_mysql_data:/var/lib/mysql
      - ./initdb/db_backup.sql:/docker-entrypoint-initdb.d/db_backup.sql:ro
    networks:
      - flasknet

  web:
    build:
      context: .
    container_name: flask_app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "5000:5000"
    networks:
      - flasknet

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    networks:
      - flasknet

networks:
  flasknet:
    driver: bridge

volumes:
  bsf_attendence_mysql_data:
